import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'Deoxs',
  description: 'Criação do Header e footer',
=======
  title: 'Equipe Deoxs',
  description: 'Generated by create next app',
>>>>>>> 11a3edf0ebac347693ed85bc60d195cbd1d7bb8a
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
